use language::operations::{make_param_doc, Operation, ParamInfo};

pub struct SetShowMessagesOp;

const DOC : &str = "Suppresses (value = 0) or enables (value = 1) game messages, including those generated by the game engine.";

pub const OP_CODE: u32 = 1107;

pub const IDENT: &str = "set_show_messages";

impl Operation for SetShowMessagesOp {
    fn op_code(&self) -> u32 {
        OP_CODE
    }

    fn documentation(&self) -> &'static str {
        DOC
    }

    fn identifier(&self) -> &'static str {
        IDENT
    }

    fn param_info(&self) -> ParamInfo {
        ParamInfo {
            num_required: 1,
            num_optional: 0,
            param_docs: vec![make_param_doc("<value>", "")],
        }
    }
}
