use language::operations::{make_param_doc, Operation, ParamInfo};

pub struct EntryPointIsAutoGeneratedOp;

const DOC : &str = "Checks that the entry point is auto-generated (in other words, there was no such entry point placed in the scene file).";

pub const OP_CODE: u32 = 1782;

pub const IDENT: &str = "entry_point_is_auto_generated";

impl Operation for EntryPointIsAutoGeneratedOp {
    fn op_code(&self) -> u32 {
        OP_CODE
    }

    fn documentation(&self) -> &'static str {
        DOC
    }

    fn identifier(&self) -> &'static str {
        IDENT
    }

    fn param_info(&self) -> ParamInfo {
        ParamInfo {
            num_required: 1,
            num_optional: 0,
            param_docs: vec![make_param_doc("<entry_no>", "")],
        }
    }
}
