use language::operations::Operation;

pub struct EntryPointIsAutoGeneratedOp;

const DOC: &str = r#"
Please write me!
Format: Please write me!
"#;

pub const OP_CODE: u16 = 1782;

pub const IDENT: &str = "entry_point_is_auto_generated";

impl Operation for EntryPointIsAutoGeneratedOp {
    fn op_code(&self) -> u16 {
        OP_CODE
    }

    fn documentation(&self) -> &'static str {
        DOC
    }

    fn identifier(&self) -> &'static str {
        IDENT
    }
}
